### ISSUE TITLE
Add travis 

### ISSUE THREAD

**Issue by marcelopostmedia** [marceloglacial/snowfall-boilerplate#23]
https://travis-ci.org/

**Comment by marceloglacial** [comment]
https://seesparkbox.com/foundry/how_and_why_we_unit_test_our_sass

**Comment by marceloglacial** [comment]
https://aws.amazon.com/getting-started/tutorials/launch-a-wordpress-website/

**Comment by marceloglacial** [comment]
https://docs.travis-ci.com/user/deployment/custom/

**Comment by marceloglacial** [comment]
https://wecodetheweb.com/2015/08/27/automating-ftp-deployment-with-travis-ci-and-gulp/

**Comment by marceloglacial** [comment]
https://medium.freecodecamp.org/advanced-automatic-deployment-with-travis-ci-1da32f7930ce
